version: 2

models:
  - name: customer
    description: "Tabla de clientes"
    columns:
      - name: c_custkey
        description: "Clave primaria del cliente"
        tests:
          - unique
          - not_null
      - name: c_name
        description: "Nombre del cliente"
      - name: c_address
        description: "Dirección del cliente"
      - name: c_phone
        description: "Número de teléfono del cliente"
      - name: c_nation_name
        description: "Nombre de la nación del cliente"
      - name: c_region_name
        description: "Nombre de la región del cliente"
      - name: c_acctbal
        description: "Saldo de la cuenta del cliente"
      - name: c_mktsegment
        description: "Segmento de mercado del cliente"
    meta:
      pk: c_custkey

  - name: orders
    description: "Tabla de pedidos"
    columns:
      - name: o_orderkey
        description: "Clave primaria del pedido"
        tests:
          - unique
          - not_null
      - name: o_custkey
        description: "Clave foránea del cliente"
        tests:
          - not_null
      - name: o_orderstatus
        description: "Estado del pedido"
      - name: o_totalprice
        description: "Precio total del pedido"
      - name: o_orderdate
        description: "Fecha del pedido"
      - name: o_orderpriority
        description: "Prioridad del pedido"
      - name: o_clerk
        description: "Cajero del pedido"
    meta:
      pk: o_orderkey
      fks:
        - column: o_custkey
          to: "{{ ref('customer') }}.c_custkey"

  - name: suppliers
    description: "Tabla de proveedores"
    columns:
      - name: s_suppkey
        description: "Clave primaria del proveedor"
        tests:
          - unique
          - not_null
      - name: s_name
        description: "Nombre del proveedor"
      - name: s_address
        description: "Dirección del proveedor"
      - name: s_nation_name
        description: "Nombre de la nación del proveedor"
      - name: s_region_name
        description: "Nombre de la región del proveedor"
      - name: s_acctbal
        description: "Saldo de la cuenta del proveedor"
      - name: s_phone
        description: "Número de teléfono del proveedor"
    meta:
      pk: s_suppkey

  - name: parts
    description: "Tabla de partes"
    columns:
      - name: p_partkey
        description: "Clave primaria de la parte"
        tests:
          - unique
          - not_null
      - name: p_name
        description: "Nombre de la parte"
      - name: p_mfgr
        description: "Fabricante de la parte"
      - name: p_brand
        description: "Marca de la parte"
      - name: p_type
        description: "Tipo de la parte"
      - name: p_size
        description: "Tamaño de la parte"
      - name: p_container
        description: "Contenedor de la parte"
      - name: p_retail_price
        description: "Precio de venta al público de la parte"
    meta:
      pk: p_partkey

  - name: partsupps
    description: "Tabla de suministros de partes"
    columns:
      - name: ps_partkey
        description: "Clave foránea de la parte"
        tests:
          - not_null
      - name: ps_suppkey
        description: "Clave foránea del proveedor"
        tests:
          - not_null
      - name: ps_availqty
        description: "Cantidad disponible de la parte"
      - name: ps_supplycost
        description: "Costo de suministro de la parte"
    meta:
      pk: [ps_partkey, ps_suppkey]
      fks:
        - column: ps_partkey
          to: "{{ ref('parts') }}.p_partkey"
        - column: ps_suppkey
          to: "{{ ref('suppliers') }}.s_suppkey"

  - name: lineitems
    description: "Tabla de elementos de línea"
    columns:
      - name: l_orderkey
        description: "Clave foránea del pedido"
        tests:
          - not_null
      - name: l_partkey
        description: "Clave foránea de la parte"
        tests:
          - not_null
      - name: l_suppkey
        description: "Clave foránea del proveedor"
        tests:
          - not_null
      - name: l_linenumber
        description: "Número de línea del elemento"
        tests:
          - not_null
      - name: l_quantity
        description: "Cantidad del elemento"
      - name: l_extendedprice
        description: "Precio extendido del elemento"
      - name: l_discount
        description: "Descuento del elemento"
      - name: l_tax
        description: "Impuesto del elemento"
      - name: l_returnflag
        description: "Bandera de devolución del elemento"
      - name: l_linestatus
        description: "Estado de la línea del elemento"
      - name: l_shipdate
        description: "Fecha de envío del elemento"
      - name: l_commitdate
        description: "Fecha de confirmación del elemento"
      - name: l_receiptdate
        description: "Fecha de recepción del elemento"
      - name: l_shipinstruct
        description: "Instrucción de envío del elemento"
      - name: l_shipmode
        description: "Modo de envío del elemento"
    meta:
      pk: [l_orderkey, l_linenumber]
      fks:
        - column: l_orderkey
          to: "{{ ref('orders') }}.o_orderkey"
        - column: l_partkey
          to: "{{ ref('parts') }}.p_partkey"
        - column: l_suppkey
          to: "{{ ref('suppliers') }}.s_suppkey"
