version: 2

sources:
  - name: db_source
    database: db_source
    schema: db_source_schema
    tables:
      - name: customer
      - name: orders
      - name: lineitem
      - name: part
      - name: partsupp
      - name: supplier
      - name: nation
        freshness: 
          null
      - name: region
        freshness: 
          null
      - name: conversion
        freshness: 
          null
    freshness: 
      warn_after:
        count: 30
        period: minute
      error_after:
        count: 24
        period: hour
    
