version: 2

seeds:
  - name: dim_Event
    description: "Datos de eventos generados mediante el archivo seed"
    columns:
      - name: e_eventkey
        description: "Clave primaria del evento."
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null

      - name: e_name
        description: "Nombre del evento."
        constraints:
          - type: not_null 
        tests:
          - not_null

      - name: e_nation_name
        description: "Nombre del país donde se lleva a cabo el evento."
        constraints:
          - type: not_null 
        tests:
          - not_null

      - name: e_start_date
        description: "Fecha de inicio del evento."
        constraints:
          - type: not_null 
        tests:
          - not_null

      - name: e_end_date
        description: "Fecha de fin del evento."
        constraints:
          - type: not_null 
        tests:
          - not_null

  - name: dim_Store
    description: "Datos de tiendas generados mediante el archivo seed"
    columns:
      - name: st_storekey
        description: "Clave primaria de la tienda."
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null

      - name: st_name
        description: "Nombre de la tienda."
        constraints:
          - type: not_null 
        tests:
          - not_null

      - name: st_nation_name
        description: "Nombre del país donde está localizada la tienda."
        constraints:
          - type: not_null 
        tests:
          - not_null